[package]
name = "logic-min"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
arrayvec = "0.7.2"
itertools = "0.10.3"
proptest = { version = "1.0.0", optional = true }

[features]
proptest1 = ["proptest"]
